company: SolidCore Services
email: zach.dyer@zachdyerdesign.com
description: >- # this means to ignore newlines until "baseurl:"
  SolidCore Services provides solutions for small businesses in Missouri. 
  We publish your content online so you can relax and let us do the heavy lifting.
  Your customers will be able to view your recent projects from any smart phone device.
  Your content will be easily searchable through Google and easy for your customers to find
  information about your company online.
icon: fas fa-mountain # company icon
navbar: 
  include: navbar.html
  darkmode: false